apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: cockroach-service
    app: ecommerce-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: cockroach-pod
    app: ecommerce-app