apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: NodePort
  selector:
    name: analytics-deploy
    app: ecommerce-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080